name: Module 00

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Exercise-00:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: install cppunit
      # run: sudo apt install -y libcppunit-dev

    - name: build
      run: make -C module-00/ex00

    - name: test
      run: make -C module-00/ex00 check

  Exercise-01:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: install cppunit
      # run: sudo apt install -y libcppunit-dev

    - name: build
      run: make -C module-00/ex00

    - name: test
      run: make -C module-00/ex00 check
