name: Module 00

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Exercise-00:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make -C module-00/ex00

    - name: Test 00
      run: make -C module-00/ex00 test-00

    - name: Test 01
      run: make -C module-00/ex00 test-01

    - name: Test 02
      run: make -C module-00/ex00 test-02

  MacOS:
    needs: Ubuntu
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make -C module-00/ex00

    - name: Test 00
      run: make -C module-00/ex00 test-00

    - name: Test 01
      run: make -C module-00/ex00 test-01

    - name: Test 02
      run: make -C module-00/ex00 test-02

  # Windows:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Build
  #     run: make -C module-00/ex00

  #   - name: Test 00
  #     run: make -C module-00/ex00 test-00

  #   - name: Test 01
  #     run: make -C module-00/ex00 test-01

  #   - name: Test 02
  #     run: make -C module-00/ex00 test-02
